"""
Feature pipeline for combining multiple quantitative indicators into a unified feature matrix.

Manages:
- Input validation across all constituent indicators
- Clean merging without accidental column overwriting
- Timestamp and index alignment
- Warmup period tracking and ready-state filtering
"""

from __future__ import annotations

from typing import Iterable, Optional, Sequence, Union
import numpy as np
import pandas as pd

from core.models import OHLCVBar
from indicators.base import Indicator, IndicatorMetadata
from indicators.series import to_dataframe
from indicators.validation import IndicatorValidationError


class FeaturePipeline:
    """
    Assembles and calculates a composite set of quantitative indicators.

    Usage:
        pipeline = FeaturePipeline([
            EMA(period=20),
            EMA(period=50),
            RSI(period=14),
            ATR(period=14),
            SessionVWAP(),
            IchimokuCloud(),
        ])
        features_df = pipeline.calculate(bars)
        warm_features = pipeline.get_warm_data(bars)
    """

    def __init__(
        self,
        indicators: Sequence[Indicator],
        include_input_columns: bool = True,
    ) -> None:
        if not indicators:
            raise ValueError("FeaturePipeline must contain at least one indicator")
        self._indicators = list(indicators)
        self.include_input_columns = include_input_columns

    @property
    def indicators(self) -> list[Indicator]:
        """List of constituent indicators."""
        return list(self._indicators)

    @property
    def max_warmup_period(self) -> int:
        """Maximum warmup period required across all configured indicators."""
        return max((ind.warmup_period for ind in self._indicators), default=0)

    @property
    def metadata(self) -> list[IndicatorMetadata]:
        """Metadata for all indicators in this pipeline."""
        return [ind.metadata for ind in self._indicators]

    @property
    def expected_output_columns(self) -> list[str]:
        """All column names generated by indicators in this pipeline."""
        cols: list[str] = []
        for ind in self._indicators:
            cols.extend(ind.output_columns)
        return cols

    def calculate(self, data: Union[pd.DataFrame, Sequence[OHLCVBar]]) -> pd.DataFrame:
        """
        Execute all indicators and assemble a unified feature matrix.

        Args:
            data: DataFrame or list of OHLCVBars.

        Returns:
            pd.DataFrame containing input columns (if configured) plus all calculated features.

        Raises:
            IndicatorValidationError: If any indicator's input requirements are not satisfied.
            ValueError: If duplicate column collision occurs.
        """
        df_raw = to_dataframe(data)

        if self.include_input_columns:
            result = df_raw.copy()
        else:
            result = pd.DataFrame(index=df_raw.index)
            if "timestamp" in df_raw.columns:
                result["timestamp"] = df_raw["timestamp"].copy()

        for ind in self._indicators:
            ind_output = ind.calculate(df_raw)

            # Collision check: Prevent silent overwrite
            for col in ind_output.columns:
                if col in result.columns:
                    raise ValueError(
                        f"Column name collision in FeaturePipeline: '{col}' generated by "
                        f"{ind.name} already exists in DataFrame. Ensure distinct indicator parameters."
                    )
                result[col] = ind_output[col]

        return result

    def is_warm(self, features_df: pd.DataFrame) -> pd.Series:
        """
        Return a boolean Series indicating which rows have passed warmup.
        A row is warm if all indicator columns are non-NaN.
        """
        feature_cols = [c for c in self.expected_output_columns if c in features_df.columns]
        if not feature_cols:
            return pd.Series(True, index=features_df.index)
        return features_df[feature_cols].notna().all(axis=1)

    def get_warm_data(self, data: Union[pd.DataFrame, Sequence[OHLCVBar]]) -> pd.DataFrame:
        """
        Calculate features and return only the warm rows where all indicators are valid.
        """
        features = self.calculate(data)
        warm_mask = self.is_warm(features)
        return features.loc[warm_mask].copy()

    def __repr__(self) -> str:
        names = ", ".join(ind.name for ind in self._indicators)
        return f"FeaturePipeline(indicators=[{names}], max_warmup={self.max_warmup_period})"
