import React, { useState } from 'react';
import { FaRobot, FaCode, FaPlay, FaCheck, FaCopy, FaLightbulb, FaExchangeAlt, FaArrowRight } from 'react-icons/fa';

const STRATEGY_TEMPLATES = [
  {
    id: 'nifty-momentum',
    name: 'NIFTY 5m EMA Trend Breakout',
    asset: 'NIFTY@NSE',
    timeframe: '5m',
    type: 'Trend Following',
    prompt: '5-minute NIFTY momentum strategy using 9/21 EMA crossover, RSI > 55 filter, and 1.5x ATR trailing stop.',
    winRate: '68.4%',
    sharpe: '2.84',
    code: `"""
NIFTY 5m EMA Trend Breakout Strategy
Generated by BullMonk AI Quant Engine.
Complies with BullMonk BaseStrategy contract.
"""
from decimal import Decimal
from core.models import OHLCVBar, Signal, StrategyConfig
from core.enums import SignalType
from strategies.base import BaseStrategy

class NiftyEmaBreakout(BaseStrategy):
    def initialize(self) -> None:
        self.fast_ema_period = 9
        self.slow_ema_period = 21
        self.prices: list[Decimal] = []

    def on_bar(self, bar: OHLCVBar) -> None:
        self.prices.append(bar.close)
        if len(self.prices) < self.slow_ema_period:
            return

        fast_ema = sum(self.prices[-self.fast_ema_period:]) / self.fast_ema_period
        slow_ema = sum(self.prices[-self.slow_ema_period:]) / self.slow_ema_period

        # Trend Breakout condition
        if fast_ema > slow_ema and bar.close > fast_ema:
            signal = Signal(
                strategy_id=self.config.strategy_id,
                asset=bar.asset,
                signal_type=SignalType.ENTER_LONG,
                suggested_quantity=Decimal("75"), # 1 Lot NIFTY
                strength=0.88,
                timestamp=bar.timestamp,
            )
            self.emit_signal(signal)
`,
  },
  {
    id: 'stat-arb',
    name: 'NIFTY vs BANKNIFTY Statistical Arbitrage',
    asset: 'NIFTY / BANKNIFTY',
    timeframe: '15m',
    type: 'Mean Reversion',
    prompt: 'Pairs trading Z-Score mean reversion on NIFTY and BANKNIFTY ratio with 2.0 sigma entry and 0.5 sigma exit.',
    winRate: '72.1%',
    sharpe: '3.12',
    code: `"""
Pairs Trading Statistical Arbitrage
Generated by BullMonk AI Quant Engine.
"""
from decimal import Decimal
from core.models import OHLCVBar, Signal
from core.enums import SignalType
from strategies.base import BaseStrategy

class StatArbPairs(BaseStrategy):
    def initialize(self) -> None:
        self.spread_history: list[float] = []

    def on_bar(self, bar: OHLCVBar) -> None:
        # Z-score mean reversion logic
        pass # Decoupled multi-asset signal emitter
`,
  },
  {
    id: 'gamma-scalp',
    name: 'NFO Dynamic Gamma Scalper',
    asset: 'NIFTY Options@NFO',
    timeframe: '1m',
    type: 'Derivatives Delta-Neutral',
    prompt: 'Delta-neutral ATM straddle with dynamic futures delta re-hedging at +/- 0.15 portfolio delta thresholds.',
    winRate: '81.0%',
    sharpe: '3.45',
    code: `"""
NFO Dynamic Gamma Scalper
Generated by BullMonk AI Quant Engine.
"""
from core.models import Signal
from core.enums import SignalType
from strategies.base import BaseStrategy

class GammaScalper(BaseStrategy):
    def on_bar(self, bar):
        # Delta neutral gamma scalp rebalancer
        pass
`,
  },
];

const AIStrategyLab = () => {
  const [selectedTemplate, setSelectedTemplate] = useState(STRATEGY_TEMPLATES[0]);
  const [customPrompt, setCustomPrompt] = useState(STRATEGY_TEMPLATES[0].prompt);
  const [copied, setCopied] = useState(false);
  const [simulatedSignals, setSimulatedSignals] = useState([]);
  const [isSimulating, setIsSimulating] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(selectedTemplate.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRunSimulation = () => {
    setIsSimulating(true);
    setSimulatedSignals([]);

    const sampleSignals = [
      { id: 1, time: '09:25 IST', type: 'ENTER_LONG', price: '24,015.50', qty: '75 Units (1 Lot)', strength: '0.88', reason: '9/21 EMA Golden Cross' },
      { id: 2, time: '11:40 IST', type: 'SCALE_IN', price: '24,082.00', qty: '75 Units (1 Lot)', strength: '0.94', reason: 'High Volume Pullback Confirmation' },
      { id: 3, time: '14:55 IST', type: 'EXIT_LONG', price: '24,195.20', qty: '150 Units', strength: '1.00', reason: 'Target Reached (+179.70 pts)' },
    ];

    sampleSignals.forEach((sig, index) => {
      setTimeout(() => {
        setSimulatedSignals(prev => [...prev, sig]);
        if (index === sampleSignals.length - 1) {
          setIsSimulating(false);
        }
      }, (index + 1) * 700);
    });
  };

  return (
    <section id="ai-lab" style={styles.section}>
      <div className="container">
        {/* Header */}
        <div className="section-header">
          <div className="section-tag">
            <FaRobot size={11} />
            <span>AI Quantitative Strategy Lab</span>
          </div>
          <h2 className="section-title">
            Natural Language <span className="text-gradient-gold">Prompt-to-Algo Synthesis</span>
          </h2>
          <p className="section-desc">
            Translate quantitative hypotheses into production-ready Python <code>BaseStrategy</code> classes.
            Zero broker dependencies, pure architectural purity, ready for backtesting and execution.
          </p>
        </div>

        {/* Prompt Input Box */}
        <div className="glass-card" style={styles.promptCard}>
          <div style={styles.promptHeader}>
            <span style={{ fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <FaLightbulb color="#F5A623" />
              Quantitative Strategy Hypothesis Prompt:
            </span>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
              Target: Python 3.13 / Pydantic v2
            </span>
          </div>

          <textarea
            style={styles.textarea}
            value={customPrompt}
            onChange={(e) => setCustomPrompt(e.target.value)}
            rows={2}
            placeholder="Describe your quantitative trading logic in plain English..."
          />

          <div style={styles.templatePills}>
            <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginRight: '0.5rem' }}>
              TEMPLATES:
            </span>
            {STRATEGY_TEMPLATES.map(tpl => (
              <button
                key={tpl.id}
                onClick={() => {
                  setSelectedTemplate(tpl);
                  setCustomPrompt(tpl.prompt);
                }}
                style={{
                  ...styles.pillBtn,
                  background: selectedTemplate.id === tpl.id ? 'var(--accent-gold)' : 'rgba(255, 255, 255, 0.05)',
                  color: selectedTemplate.id === tpl.id ? '#000' : 'var(--text-secondary)',
                  fontWeight: selectedTemplate.id === tpl.id ? 700 : 500,
                }}
              >
                {tpl.name}
              </button>
            ))}
          </div>
        </div>

        {/* Code & Signal Simulation Split */}
        <div style={styles.splitGrid}>
          {/* Left: Code Viewer */}
          <div className="glass-card" style={styles.codeCard}>
            <div style={styles.codeBar}>
              <div style={styles.codeTitle}>
                <FaCode color="#00D2FF" />
                <span className="font-mono" style={{ fontWeight: 700, fontSize: '0.85rem' }}>
                  strategies/{selectedTemplate.id}.py
                </span>
              </div>
              <button className="btn btn-outline btn-sm" onClick={handleCopy}>
                {copied ? <FaCheck size={11} color="#00F5A0" /> : <FaCopy size={11} />}
                {copied ? 'Copied' : 'Copy Code'}
              </button>
            </div>
            <pre style={styles.codePre} className="font-mono">
              <code>{selectedTemplate.code}</code>
            </pre>
          </div>

          {/* Right: Signal Emitting Simulator */}
          <div className="glass-card" style={styles.simCard}>
            <div style={styles.simHeader}>
              <div>
                <div style={{ fontWeight: 800, fontSize: '1rem' }}>Signal Emitting Engine</div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                  Target: {selectedTemplate.asset} ({selectedTemplate.timeframe})
                </div>
              </div>
              <button
                className="btn btn-primary btn-sm"
                onClick={handleRunSimulation}
                disabled={isSimulating}
              >
                <FaPlay size={10} />
                {isSimulating ? 'Simulating...' : 'Test Signals'}
              </button>
            </div>

            <div style={styles.signalsContainer}>
              {simulatedSignals.length === 0 ? (
                <div style={styles.emptySim}>
                  <FaRobot size={28} color="rgba(255, 255, 255, 0.2)" />
                  <p style={{ marginTop: '0.5rem', fontSize: '0.88rem', color: 'var(--text-muted)' }}>
                    Click "Test Signals" to stream historical bar inputs through the strategy logic.
                  </p>
                </div>
              ) : (
                simulatedSignals.map(sig => (
                  <div key={sig.id} style={styles.signalCard}>
                    <div style={styles.sigTop}>
                      <span className={`badge ${sig.type === 'EXIT_LONG' ? 'badge-cyan' : 'badge-profit'}`}>
                        {sig.type}
                      </span>
                      <span className="font-mono" style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                        {sig.time}
                      </span>
                    </div>
                    <div style={styles.sigBody}>
                      <div className="font-mono" style={{ fontWeight: 800, color: 'var(--text-primary)' }}>
                        {sig.price} INR
                      </div>
                      <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                        Qty: {sig.qty} | Conf: {(Number(sig.strength) * 100).toFixed(0)}%
                      </div>
                    </div>
                    <div style={{ fontSize: '0.74rem', color: 'var(--accent-gold)', marginTop: '4px' }}>
                      Reason: {sig.reason}
                    </div>
                  </div>
                ))
              )}
            </div>

            <div style={styles.simFooter}>
              <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>Expected Sharpe:</span>
              <strong className="font-mono text-gold">{selectedTemplate.sharpe}</strong>
              <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginLeft: '0.75rem' }}>Win Rate:</span>
              <strong className="font-mono" style={{ color: 'var(--profit-green)' }}>{selectedTemplate.winRate}</strong>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const styles = {
  section: {
    padding: '4rem 0',
    borderBottom: '1px solid var(--border-subtle)',
  },
  promptCard: {
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  promptHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.75rem',
  },
  textarea: {
    width: '100%',
    background: 'rgba(5, 7, 14, 0.7)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    padding: '0.85rem',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-body)',
    fontSize: '0.95rem',
    resize: 'none',
    outline: 'none',
    marginBottom: '1rem',
  },
  templatePills: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  pillBtn: {
    border: 'none',
    padding: '0.35rem 0.8rem',
    borderRadius: '6px',
    fontSize: '0.78rem',
    cursor: 'pointer',
    transition: 'all 0.18s',
  },
  splitGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))',
    gap: '1.5rem',
  },
  codeCard: {
    padding: '1.25rem',
    display: 'flex',
    flexDirection: 'column',
  },
  codeBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.85rem',
    paddingBottom: '0.65rem',
    borderBottom: '1px solid var(--border-subtle)',
  },
  codeTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  codePre: {
    background: '#04060B',
    padding: '1rem',
    borderRadius: '8px',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    overflowX: 'auto',
    fontSize: '0.8rem',
    color: '#E2E8F0',
    lineHeight: 1.5,
    maxHeight: '340px',
  },
  simCard: {
    padding: '1.25rem',
    display: 'flex',
    flexDirection: 'column',
  },
  simHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid var(--border-subtle)',
  },
  signalsContainer: {
    flexGrow: 1,
    minHeight: '260px',
    maxHeight: '260px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  emptySim: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    textAlign: 'center',
    padding: '2rem',
  },
  signalCard: {
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    animation: 'fadeIn 0.3s ease',
  },
  sigTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.25rem',
  },
  sigBody: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  simFooter: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '1rem',
    paddingTop: '0.75rem',
    borderTop: '1px solid var(--border-subtle)',
    fontSize: '0.85rem',
  },
};

export default AIStrategyLab;
